Esercizio 1/3 Estraiamo la tabella dimproduct dal database AdventureWorks, e valutiamo quanto segue: • Quanti dati ci sono in totale? • Quali sono i metadati? • Stampiamo il primo elemento • Stampiamo l'ultimo elemento • Riusciamo a stampare cinque elementi a caso? • Quali sono i colori disponibili?
Esercizio 2/3 • In media quanto pesano i prodotti (per questo esercizio, ignoriamo l'unità di misura, ma usiamo solo i valori della colonna relativa)? • Quanto pesa il più leggero? • Quanto pesa il più pesante? • Quanti prodotti pesano più di 100? • Quanto costano in media i prodotti (colonna DealerPrice)? • Quali sono i quartili dei prezzi?
Esercizio 3/3 • Qual è il prezzo medio per i prodotti di colore blu? • Qual è il prezzo medio per i prodotti di colore rosso o nero? • Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg? • Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42, peso oltre i 10 Kg e colore argento? • Visualizziamo lo StandardCost e il DealerPrice degli ultimi 20 elementi del dataset: quali sono le differenze? C'è un pattern? C'è qualche elemento che non lo segue?

In [1]:
#Estraiamo la tabella dimproduct dal database AdventureWorks
import os
import dotenv
import sqlalchemy
import pandas as pd

dotenv.load_dotenv(dotenv_path="cred.env", override=True)

username = os.getenv("username") 
password = os.getenv("password") 
host = os.getenv("host") 
dbname = os.getenv("dbname") 

connection_string = "mysql+pymysql://"+username+":"+password+"@"+host+"/"+dbname 

db_engine = sqlalchemy.create_engine(connection_string)

query = "SELECT * FROM dimproduct"
tabella = pd.read_sql(query, db_engine)

In [2]:
#Dati totali
tabella.shape

(606, 36)

In [3]:
#Metadati
tabella.columns

Index(['ProductKey', 'ProductAlternateKey', 'ProductSubcategoryKey',
       'WeightUnitMeasureCode', 'SizeUnitMeasureCode', 'EnglishProductName',
       'SpanishProductName', 'FrenchProductName', 'StandardCost',
       'FinishedGoodsFlag', 'Color', 'SafetyStockLevel', 'ReorderPoint',
       'ListPrice', 'Size', 'SizeRange', 'Weight', 'DaysToManufacture',
       'ProductLine', 'DealerPrice', 'Class', 'Style', 'ModelName',
       'LargePhoto', 'EnglishDescription', 'FrenchDescription',
       'ChineseDescription', 'ArabicDescription', 'HebrewDescription',
       'ThaiDescription', 'GermanDescription', 'JapaneseDescription',
       'TurkishDescription', 'StartDate', 'EndDate', 'Status'],
      dtype='object')

In [4]:
#Stampo il primo elemento
tabella.head(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [5]:
#Stampo l'ultimo elemento
tabella.tail(1)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [6]:
#Stampo 5 elementi casuali
tabella.sample(5)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
89,90,LE-8000,NaN,None,None,External Lock Washer 2,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
546,547,PD-R853,13.0,G,None,HL Road Pedal,Pedal de carretera GA,Pédale de vélo de route HL,35.96,1,...,松紧可调的高档无扣带式脚踏。,دواستان من أعلى الطرازات بقوة شدّ يمكن تعديلها.,דוושות נטולות חבקים מהשורה הראשונה עם מאמץ מתכ...,คันถีบระดับเยี่ยม ไม่มีคลิป ปรับความตึงได้,Top-Pedale ohne Pedalhaken mit anpassbarer Spa...,テンション調整が可能な最高級クリップレス ペダル。,Gerginliği ayarlanabilen gerginlikli en üst sı...,2013-07-01,NaT,Current
333,334,BK-R50B-60,2.0,LB,CM,"Road-650 Black, 60","Carretera: 650, negra, 60","Vélo de route 650 noir, 60",413.15,1,...,此自行车经济实惠，具有我们的高档车型所拥有的许多功能。相同的车灯、刚架以及我们驰名业界的快速...,إنها دراجة ذات سعر مناسب لإمكاناتها كما تتمتع ...,אופניים המהווים תמורה נאותה למחירם ובעלי רבות ...,จักรยานที่ให้ความคุ้มค่า ด้วยคุณสมบัติพิเศษมาก...,"""Kostengünstiges Rad mit vielen Funktionen uns...",最高級モデルの特色の多くを備えた値打ち価格の自転車です。ハイエンド クラスに匹敵する軽量高剛...,Değerine uygun olarak fiyatlandırılan bisiklet...,2011-07-01,2007-12-28,None
388,389,BK-R64Y-48,2.0,LB,CM,"Road-550-W Yellow, 48","Carretera: 550 para mujer, amarilla, 48","Vélo de route 550 -W - jaune, 48",605.65,1,...,使用的技术与我们所有的公路系列自行车完全相同，但车架尺寸专为女士设计。完美的全能自行车，可作...,ولها نفس التقنية المتوفرة في جميع دراجات سلسلة...,"טכנולוגיה זהה לזו המצוי באופני סדרת ""כביש"" שלנ...",เทคโนโลยีเดียวกับจักรยานรุ่น Road ทั้งหมด แต่ใ...,Dieselbe Technologie wie bei allen Rädern unse...,ロード シリーズの自転車と同じ技術を使用した女性用サイズのフレームで、ロードにも競技にも適し...,"""Yol serisi bisikletlerimizle aynı teknoloji, ...",2012-07-01,2008-12-27,None
239,240,FR-R92R-62,14.0,LB,CM,"HL Road Frame - Red, 62","Cuadro de carretera GA: rojo, 62","Cadre de vélo de route HL - rouge, 62",868.63,1,...,重量最轻、质量最好的铝制车架采用最新的合金材质；经过焊接和热处理，坚固牢靠。我们创新的设计确...,لقد تم صناعة هيكل دراجتنا الألومنيوم الأخف وزن...,מסגרת האלומיניום הקלה והאיכותית ביותר שלנו עשו...,เฟรมอลูมิเนียมคุณภาพสูงสุดและน้ำหนักเบาที่สุด ...,Unser leichtester und hochwertigster Aluminium...,最新の合金で作られた最軽量/最高品質のアルミニウム フレームで、強度を得るために溶接および熱...,"""En yeni alaşımdan imal edilme, en hafif ve en...",2013-07-01,NaT,Current

In [7]:
#Quali sono i colori disponibili?
tabella["Color"].unique()

array(['NA', 'Black', 'Silver', 'Red', 'White', 'Blue', 'Multi', 'Yellow',
       'Grey', 'Silver/Black'], dtype=object)

In [8]:
#Peso dei prodotti medio
tabella["Weight"].mean().round(2)

56.19

In [9]:
#Il prodotto più leggero
tabella["Weight"].min()

2.12

In [10]:
#Il prodotto più pesante
tabella["Weight"].max()

1050.0

In [11]:
#I prodotti Weight > 100 
tabella[tabella["Weight"] > 100]

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
179,180,RM-M464,NaN,G,None,LL Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
180,181,RM-M692,NaN,G,None,ML Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
181,182,RM-M823,NaN,G,None,HL Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
182,183,RM-R436,NaN,G,None,LL Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
183,184,RM-R600,NaN,G,None,ML Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
184,185,RM-R800,NaN,G,None,HL Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
185,186,RM-T801,NaN,G,None,Touring Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
412,413,FW-R623,17.0,G,None,LL Road Front Wheel,Rueda de carretera delantera GB,Roue avant de vélo de route LL,37.99,1,...,适用于入门级骑乘者的公路型备用前轮。,عجلة طريق أمامية بديلة لقائدي الدراجات المبتدئين.,גלגל חלופי קדמי לרכיבת כביש לרוכב המתחיל.,ล้อหน้าจักรยานภูเขาอะไหล่สำหรับนักปั่นระดับเริ...,Ersatzvorderrad für Einsteiger.,初心者向けの交換用フロント ロード ホイール。,Başlangıç seviyesindeki sürücüler için yedek ö...,2012-07-01,2008-12-27,None
413,414,FW-R762,17.0,G,None,ML Road Front Wheel,Rueda de carretera delantera GM,Roue avant de vélo de route ML,110.28,1,...,坚固的合金具有快拆式车毂。,تتميز بوجود سبيكة قوية تحتوي على محور عجلة سري...,סגסוגת איתנה מאפיינת את מנגנון השחרור המהיר של...,ดุมล้ออัลลอยด์ที่ทนทาน ถอดได้อย่างรวดเร็ว,Robustes Design mit Schnellspann-Nabe.,頑丈な合金による、クイックリリース ハブ。,"""Dayanıklı alaşım, kolay sökülebilen göbek içe...",2012-07-01,2008-12-27,None
414,415,FW-R820,17.0,G,None,HL Road Front Wheel,Rueda de carretera delantera GA,Roue avant de vélo de route HL,146.55,1,...,具有双层轮缘的坚固车轮。,عجلة قوية بإطار معدني ذي طبقتين.,גלגל חזק עם חישוק בעל הלחמה כפולה.,ล้อที่แข็งแกร่งพร้อมขอบล้อผนังสองชั้น,Starkes Rad mit doppelt beschichteter Felge.,ダブルウォール リムを持つ頑丈なホイール。,İki duvarlı jantlı güçlü tekerlek.,2012-07-01,2008-12-27,None
421,422,RW-R623,17.0,G,None,LL Road Rear Wheel,Rueda de carretera trasera GB,Roue arrière de vélo de route LL,49.98,1,...,适用于入门级骑乘者的公路型备用前轮。,عجلة طريق أمامية بديلة لقائدي الدراجات المبتدئين.,גלגל חלופי קדמי לרכיבת כביש לרוכב המתחיל.,ล้อหน้าจักรยานภูเขาอะไหล่สำหรับนักปั่นระดับเริ...,Ersatzhinterrad für Einsteiger.,初心者向けの交換用リア ロード ホイール。,Başlangıç seviyesinde sürücüler için yedek ark...,2012-07-01,2008-12-27,None
422,423,RW-R762,17.0,G,None,ML Road Rear Wheel,Rueda de carretera trasera GM,Roue arrière de vélo de route ML,122.27,1,...,带不锈钢辐条的铝合金轮缘；特别为提速而设计。,إطار معدني مصنوع من سبيكة الألومنيوم بقضبان شع...,חישוק מסגסוגת אלומיניום עם חישורים מפלדת אל-חל...,ขอบอลูมิเนียมอัลลอยด์พร้อมซี่ล้อสเตนเลส สำหรับ...,Felge aus Aluminiumlegierung mit Speichen aus ...,高速走行用のステンレス製スポークを備えたアルミニウム合金リム。,Paslanmaz çelik telli alüminyum alaşımı jantla...,2012-07-01,2008-12-27,None
423,424,RW-R820,17.0,G,None,HL Road Rear Wheel,Rueda de carretera trasera GA,Roue arrière de vélo de route HL,158.53,1,...,具有双层轮缘的坚固后轮。,عجلة خلفية قوية بإطار معدني ذي طبقتين.,גלגל אחורי חזק עם חישוק בעל הלחמה כפולה.,ล้อหลังที่แข็งแกร่งพร้อมขอบล้อผนังสองชั้น,Starkes Hinterrad mit doppelt beschichteter Fe...,ダブルウォール リムを持つ頑丈なリア ホイール。,İki duvarlı jantlı güçlü arka tekerlek.,2012-07-01,2008-12-27,None
500,501,RD-2308,9.0,G,None,Rear Derailleur,Desviador trasero,Dérailleur arrière,53.93,1,...,宽连杆设计。,تصميم عريض الوصلات.,עיצוב רחב-חוליות.,การออกแบบให้มีจุดเชื่อมกว้าง,Wide-Link-Design.,ワイドリンク デザイン。,Geniş bağlantılı tasarım.,2013-07-01,NaT,Current
513,514,RB-9231,6.0,G,None,Rear Brakes,Frenos traseros,Freins arrière,47.29,1,...,None,None,None,None,None,None,None,2013-07-01,NaT,Current
541,542,PD-M282,13.0,G,None,LL Mountain Pedal,Pedal de montaña GB,Pédale de VTT LL,17.98,1,...,展开式踏板便于您穿任何鞋子骑乘；适用于各种情况。,هيكل أساسي واسع بحيث يمكنك القيادة بأي حذاء، و...,משטח דוושות מורחב המתאים לרכיבה בכל סוגי הנעלי...,คันถีบขนาดใหญ่ สำหรับการขับขี่ด้วยรองเท้าชนิดใ...,Größere Fläche für Komfort in allen Schuhen.,靴を選ばない拡張プラットフォームなので、オールラウンド ライディングに最適です。,"""Geniş pedalı sayesinde her tür ayakkabıyla sü...",2013-07-01,NaT,Current
542,543,PD-M340,13.0,G,None,ML Mountain Pedal,Pedal de montaña GM,Pédale de VTT ML,27.57,1,...,无扣带式脚踏轻型耐用且松紧可调。,دواسة خفيفة الوزن شديدة التحمّل بلا مشابك وذات...,דוושה עמידה נטולת חבקים עם מאמץ מתכוונן.,คันถีบน้ำหนักเบา ทนทาน ไม่มีคลิป และสามารถปรับ...,Leichte Pedale ohne Pedalhaken mit anpassbarer...,軽量で耐久性に優れ、テンション調整が可能なクリップレス ペダル。,"""Hafif, dayanıklı klipssiz pedal, gerginliği a...",2013-07-01,NaT,Current
543,544,PD-M562,13.0,G,None,HL Mountain Pedal,Pedal de montaña GA,Pédale de VTT HL,35.96,1,...,不锈钢材质；易于去泥。,مصنوعة من الفولاذ الذي لا يصدأ، والذي تم تصميم...,פלדת אל-חלד; עיצוב המשיר בוץ בקלות.,โลหะสเตนเลส ได้รับการออกแบบให้สลัดโคลนออกได้ง่าย,Edelstahl; schmutzabweisendes Design.,ステンレス製で、泥を簡単に払い落せるデザインです。,"""Paslanmaz çelik, çamuru üzerinden kolayca ata...",2013-07-01,NaT,Current
544,545,PD-R347,13.0,G,None,LL Road Pedal,Pedal de carretera GB,Pédale de vélo de route LL,17.98,1,...,无扣带式脚踏 – 铝制。,دواستان بلا مشابك مصنوعتان من الألومنيوم.,דוושות ללא חבקים – אלומיניום.,คันถีบไม่มีคลิป - อลูมิเนียม,Pedale ohne Pedalhaken - Aluminium.,クリップレス ペダル (アルミニウム)。,Klipssiz pedallar - alüminyum.,2013-07-01,NaT,Current
545,546,PD-R563,13.0,G,None,ML Road Pedal,Pedal de carretera GM,Pédale de vélo de route ML,27.57,1,...,轻型铝合金结构。,تركيبة سبيكة ألومنيوم خفيفة الوزن.,מבנה סגסוגת אלומיניום קל משקל.,โครงสร้างอลูมิเนียมอัลลอยด์น้ำหนักเบา,Leichte Aluminiumlegierung.,軽量アルミニウム合金構造。,Hafif alüminyum alaşımı konstrüksiyon.,2013-07-01,NaT,Current
546,547,PD-R853,13.0,G,None,HL Road Pedal,Pedal de carretera GA,Pédale de vélo de route HL,35.96,1,...,松紧可调的高档无扣带式脚踏。,دواستان من أعلى الطرازات بقوة شدّ يمكن تعديلها.,דוושות נטולות חבקים מהשורה הראשונה עם מאמץ מתכ...,คันถีบระดับเยี่ยม ไม่มีคลิป ปรับความตึงได้,Top-Pedale ohne Pedalhaken mit anpassbarer Spa...,テンション調整が可能な最高級クリップレス ペダル。,Gerginliği ayarlanabilen gerginlikli en üst sı...,2013-07-01,NaT,Current
554,555,FB-9873,6.0,G,None,Front Brakes,Frenos delanteros,Freins avant,47.29,1,...,全天候刹车垫；通过增加与轮缘的接触面积来提供优异的制动功能。,تحتوي على بطانات (تيل) فرامل، تناسب كافة الظرو...,רפידות מעצור המתאימות לכל מזג אוויר; מספקות עצ...,ยางเบรกสำหรับทุกสภาพอากาศ เพื่อการหยุดที่มั่นใ...,Allwetter-Bremsbeläge für erstklassiges Bremse...,全天候型ブレーキ パッドを採用し、リムに広い表面積を適用することにより優れた制動力を提供します。,"""Tüm hava durumlarına uygun fren pedleri, jant...",2013-07-01,NaT,Current
555,556,CS-4759,8.0,G,None,LL Crankset,Bielas GB,Pédalier LL,77.92,1,...,极其坚实的脚踏轴。,محور دوران صلب فائق الأداء.,ציר קשיח במיוחד.,เพลาล้อสุดแกร่ง,Extrem robuste Achse.,最強の剛性を誇るスピンドル。,Çok sağlam mil.,2013-07-01,NaT,Current
556,557,CS-6583,8.0,G,None,ML Crankset,Bielas GM,Pédalier ML,113.88,1,...,高强度的曲臂。,ذراع تدوير شديد القوة.,זרוע ארכובה עתירת עוצמה.,คันบังคับแข็งแรงเป็นพิเศษ,Robuster Pedalarm.,高強度クランク アーム。,Çok güçlü krank kolu.,2013-07-01,NaT,Current
557,558,CS-9183,8.0,G,None,HL Crankset,Bielas GA,Pédalier HL,179.82,1,...,三重齿盘；铝制曲臂；完美变速。,مجموعة تدوير ثلاثية، وذراع تدوير ألومنيوم، وإم...,"ערכת ארכובה משולשת, זרוע ארכובה מאלומיניום, חי...",ชุดควบคุมสามชั้น คันบังคับอลูมิเนียม และการเปล...,Dreifach-Kurbelsatz; Aluminium-Pedalarm; tadel...,トリプル クランクセット、アルミニウム クランク アーム、完璧なシフト。,"""Üçlü ruble, alüminyum krank kolu, takılmadan ...",2013-07-01,NaT,Current
600,601,BB-7421,5.0,G,None,LL Bottom Bracket,Eje de pedalier GB,Axe de pédalier LL,23.97,1,...,铬钢。,الفولاذ الكرومولي,פלדת כרומולי (כרום-מולובדניום),โลหะโครโมลี,Chromstahl.,クロム鋼。,Kromoli çelik.,2013-07-01,NaT,Current
601,602,BB-8107,5.0,G,None,ML Bottom Bracket,Eje de pedalier GM,Axe de pédalier ML,44.95,1,...,铝合金车圈；大直径脚蹬轴。,فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...,כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.,ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่,Außenringe aus Aluminiumlegierung; Radachse mi...,アルミニウム合金カップ、大径スピンドル。,Alüminyum alaşımı orta göbekler; geniş çaplı mil.,2013-07-01,NaT,Current
602,603,BB-9108,5.0,G,None,HL Bottom Bracket,Eje de pedalier GA,Axe de pédalier HL,53.94,1,...,铝合金车圈和空心轴。,فناجين من سبيكة الألومنيوم ومحور أجوف.,כיסויים מסגסוגת אלומיניום וציר חלול.,ดุมอลูมิเนียมอัลลอยด์และเพลากลวง,Außenringe aus Aluminiumlegierung und hohle Ac...,アルミニウム合金カップとホロー アクスル。,Alüminyum alaşımı orta göbekler ve içi boş aks.,2013-07-01,NaT,Current

In [12]:
# Costo medio prodotti
tabella["DealerPrice"].mean().round(2)

448.6

In [13]:
#Quartili dei prezzi
tabella["DealerPrice"].describe().round(2)

count     395.00
mean      448.60
std       503.23
min         1.37
25%        41.99
50%       218.45
75%       722.59
max      2146.96
Name: DealerPrice, dtype: float64

In [14]:
# Prezzo medio prodotti colore blu
tabella[tabella["Color"] == "Blue"]["DealerPrice"].mean().round(2)

516.06

In [15]:
#Prezzo medio prodotti rossi o neri
tabella[(tabella["Color"] == "Red") | (tabella["Color"] == "Black")]["DealerPrice"].mean().round(2)

550.25

In [16]:
#Prezzo massimo prodotti di taglia 42 e peso oltre i 10kg
tabella[(tabella["Size"] == "42") & (tabella["Weight"] > 10)]["DealerPrice"].max()

2039.994

In [17]:
# Nome e costo produzione prodotti taglia 42, peso oltre 10kg e colore argento
tabella[(tabella["Size"] == "42") & (tabella["Weight"] > 10) & (tabella["Color"] == "Silver")][["EnglishProductName", "StandardCost"]]

            EnglishProductName  StandardCost
344    Mountain-100 Silver, 42       1912.15
353    Mountain-200 Silver, 42       1117.86
354    Mountain-200 Silver, 42       1265.62
588  Mountain-400-W Silver, 42        419.78
591    Mountain-500 Silver, 42        308.22

In [18]:
#Stampo ultimi 20 elementi StandardCost e DealerPrice
tabella[["StandardCost", "DealerPrice"]].tail(20)

     StandardCost  DealerPrice
586        419.78      461.694
587        419.78      461.694
588        419.78      461.694
589        419.78      461.694
590        308.22      338.994
591        308.22      338.994
592        308.22      338.994
593        308.22      338.994
594        308.22      338.994
595        294.58      323.994
596        294.58      323.994
597        294.58      323.994
598        294.58      323.994
599        294.58      323.994
600         23.97       32.394
601         44.95       60.744
602         53.94       72.894
603        343.65      323.994
604        343.65      323.994
605        343.65      323.994

Quali sono le differenze? C'è un pattern? C'è qualche elemento che non lo segue?

DealerPrice è tipicamente ~10% più alto di StandardCost, ovvero il margine di vendita.
Le righe 603-605 hanno StandardCost maggiore di DealerPrice, quindi prodotti venduti in perdita, probabilmente in liquidazione o saldo.
Molti valori duplicati, probabilmente varianti dello stesso prodotto.

Esercizio 2: Dataset: amazon.csv. Valutiamo la dimensione del dataset • Visualizziamo dieci righe a caso; • Osserviamo quali sono i nomi di colonna; • Il dataset è bilanciato, ovvero, il numero di recensioni positive è uguale a quello delle negative, oppure no?

In [19]:
amazon_df = pd.read_csv("amazon.csv")
#Dimensione dataset
amazon_df.shape

(20000, 2)

In [20]:
#Stampo dieci righe casuali
amazon_df.sample(10)

                                              reviewText  Positive
12176  Does not work how it says it will.Not worth th...         0
17607  This *game* wants my phone # and info, network...         0
15697  A steady hand gets you though the maze. Could ...         1
5814   I use this app when I have things to remember ...         1
15089  This is a nicely designed basic math review ap...         1
9043   This must be some junk ported over from the iP...         0
7631   I have no recollection of ever having installe...         0
1704   I've had this app for over a year at this vers...         0
19166  This is nearly as good and challenging as Angr...         1
3529   This app is so addicting. Some of the combinat...         1

In [21]:
#Stampo nomi colonne
amazon_df.columns

Index(['reviewText', 'Positive'], dtype='object')

In [22]:
#Controllo se numero recensioni positive sono uguali a quelle negative
rec_positive = amazon_df["Positive"] == 1
rec_negative = amazon_df["Positive"] == 0

print("Recensioni positive = ", rec_positive.sum())
print("Recensioni negative = ", rec_negative.sum())

print("recensioni positive maggiori di quelle negative")

Recensioni positive =  15233
Recensioni negative =  4767
recensioni positive maggiori di quelle negative

Esercizio 3: Il dataset diabetes.csv raccoglie persone con diabete o meno, e il valore di diverse variabili fisiologiche dei pazienti. • Osserviamone le dimensioni e un'anteprima di cinque righe; • Prendiamoci un po' di tempo per dare un'occhiata ai metadati delle colonne; • Stampiamo dei descrittori statistici del dataset; • Selezioniamo i dati relativi a diverse fasce di età: 20-29, 30-39, 40-50; • Qual è la media della pressione sanguigna diastolica per le diverse fasce di età?

In [23]:
diabetes_df = pd.read_csv("diabetes.csv")
#stampo dimensioni
diabetes_df.shape

(768, 9)

In [24]:
#cinque righe casuali
diabetes_df.sample(5)

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
670,6,165,68,26,168,33.6,0.631,49,0
702,1,168,88,29,0,35.0,0.905,52,1
583,8,100,76,0,0,38.7,0.190,42,0
136,0,100,70,26,50,30.8,0.597,21,0
284,2,108,80,0,0,27.0,0.259,52,1

In [25]:
#metadati colonne
diabetes_df.columns

Index(['Number of times pregnant',
       'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
       'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)',
       '2-Hour serum insulin (mu U/ml)',
       'Body mass index (weight in kg/(height in m)^2)',
       'Diabetes pedigree function', 'Age (years)', 'Class variable'],
      dtype='object')

In [26]:
#Stampo dei descrittori statistici del dataset
diabetes_df.describe().round(2)

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
count,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00
mean,3.85,120.89,69.11,20.54,79.80,31.99,0.47,33.24,0.35
std,3.37,31.97,19.36,15.95,115.24,7.88,0.33,11.76,0.48
min,0.00,0.00,0.00,0.00,0.00,0.00,0.08,21.00,0.00
25%,1.00,99.00,62.00,0.00,0.00,27.30,0.24,24.00,0.00
50%,3.00,117.00,72.00,23.00,30.50,32.00,0.37,29.00,0.00
75%,6.00,140.25,80.00,32.00,127.25,36.60,0.63,41.00,1.00
max,17.00,199.00,122.00,99.00,846.00,67.10,2.42,81.00,1.00

In [27]:
#Seleziono i dati relativi a diverse fasce di età: 20-29, 30-39, 40-50
fascia_20_29 = diabetes_df[(diabetes_df["Age (years)"] >= 20) & (diabetes_df["Age (years)"] <= 29)]
fascia_30_39 = diabetes_df[(diabetes_df["Age (years)"] >= 30) & (diabetes_df["Age (years)"] <= 39)]
fascia_40_50 = diabetes_df[(diabetes_df["Age (years)"] >= 40) & (diabetes_df["Age (years)"] <= 50)]

#Media della pressione sanguigna diastolica per le diverse fasce di età
print("Media fascia 20-29: ", fascia_20_29["Diastolic blood pressure (mm Hg)"].mean().round(2))
print("Media fascia 30-39: ", fascia_30_39["Diastolic blood pressure (mm Hg)"].mean().round(2))
print("Media fascia 40-50: ", fascia_40_50["Diastolic blood pressure (mm Hg)"].mean().round(2))

Media fascia 20-29:  65.35
Media fascia 30-39:  69.67
Media fascia 40-50:  74.21

Esercizio 4: Il dataset insurance.csv contiene dati rispetto a caratteristiche e abitudini delle persone, e della zona in cui vivono, rispetto ai costi individuali per le cure mediche come premio per le assicurazioni sulla salute. • Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; • Quali sono le medie di charges rispetto a region? Ci sono differenze significative? • E rispetto a smoker? E a sex? • Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?

In [28]:
insurance_df = pd.read_csv("insurance.csv")
#Visualizzo le dimensioni, nomi colonne e un'anteprima
print(insurance_df.shape)

print(insurance_df.columns)

insurance_df

(1338, 7)
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [29]:
#Media di charges rispetto a region
insurance_df.groupby("region")["charges"].mean().round(2)

region
northeast    13406.38
northwest    12417.58
southeast    14735.41
southwest    12346.94
Name: charges, dtype: float64

In [30]:
#Media di charges rispetto a smoker
insurance_df.groupby("smoker")["charges"].mean().round(2)

smoker
no      8434.27
yes    32050.23
Name: charges, dtype: float64

In [31]:
#Media di charges rispetto a sex
insurance_df.groupby("sex")["charges"].mean().round(2)

sex
female    12569.58
male      13956.75
Name: charges, dtype: float64

Il fumo è il fattore più significativo sui costi assicurativi, molto più di regione o sesso.

In [32]:
#Descrittori statistici di bmi 
insurance_df["bmi"].describe().round(2)

count    1338.00
mean       30.66
std         6.10
min        15.96
25%        26.30
50%        30.40
75%        34.69
max        53.13
Name: bmi, dtype: float64

In [33]:
#minimo di charges rispetto ai quartili di bmi
q1 = insurance_df[insurance_df["bmi"] <= 26.30]
q2 = insurance_df[(insurance_df["bmi"] > 26.30) & (insurance_df["bmi"] <= 30.40)]
q3 = insurance_df[(insurance_df["bmi"] > 30.40) & (insurance_df["bmi"] <= 34.69)]
q4 = insurance_df[insurance_df["bmi"] > 34.69]

print("Primo quartile: ", "Minimo: ", q1["charges"].min())
print("Secondo quartile: ", "Minimo: ", q2["charges"].min())
print("Terzo quartile: ", "Minimo: ", q3["charges"].min())
print("Quarto quartile: ", "Minimo: ", q4["charges"].min())

Primo quartile:  Minimo:  1121.8739
Secondo quartile:  Minimo:  1131.5066
Terzo quartile:  Minimo:  1135.9407
Quarto quartile:  Minimo:  1141.4451

In [34]:
#media di charges rispetto ai quartili di bmi
print("Primo quartile: ", "Media: ", q1["charges"].mean().round(2))
print("Secondo quartile: ", "Media: ", q2["charges"].mean().round(2))
print("Terzo quartile: ", "Media: ", q3["charges"].mean().round(2))
print("Quarto quartile: ", "Media: ", q4["charges"].mean().round(2))

Primo quartile:  Media:  10360.66
Secondo quartile:  Media:  11407.83
Terzo quartile:  Media:  14358.17
Quarto quartile:  Media:  16987.94

In [35]:
#massimo di charges rispetto ai quartili di bmi
print("Primo quartile: ", "Massimo: ", q1["charges"].max())
print("Secondo quartile: ", "Massimo: ", q2["charges"].max())
print("Terzo quartile: ", "Massimo: ", q3["charges"].max())
print("Quarto quartile: ", "Massimo: ", q4["charges"].max())

Primo quartile:  Massimo:  38245.59327
Secondo quartile:  Massimo:  62592.87309
Terzo quartile:  Massimo:  60021.39897
Quarto quartile:  Massimo:  63770.42801

Esercizio 5: Il dataset pokemon.csv contiene un database di Pokémon, con dati quali nome, tipi di attacco, valori di attacco/difesa/eccetera, e se sono o meno leggendari. • Verifichiamo la dimensione, un'anteprima e osserviamo i nomi di colonna; • È verosimile che la prima colonna dovrebbe essere un indice? • Confrontiamolo con l'indice messo automaticamente da Pandas: combaciano? • Se no, settare la prima colonna come indice. Quali sono i Pokémon leggendari? • E quali sono i leggendari di tipo 1 Grass? • E leggendari di tipo 1 Ice o Fire? • Trasformiamo la colonna Name nell'indice; • Quali sono i Pokémon della prima generazione con attacco > 50 e HP < 60?

In [36]:
pokemon_df = pd.read_csv("pokemon.csv")

In [37]:
#Dimensione, nomi colonne e anteprima
print(pokemon_df.shape)
print(pokemon_df.columns)
pokemon_df

(800, 13)
Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

È verosimile che la prima colonna dovrebbe essere un indice? Confrontiamolo con l'indice messo automaticamente da Pandas: combaciano?

La colonna "#" è un indice e non corrisponde con l'indice messo automaticamente con Pandas.

In [45]:
#Setto la prima colonna "#" come indice
pokemon_df.set_index("#", inplace=True)  # ora funziona

In [49]:
#Pokemon Leggendari?
pokemon_df[pokemon_df["Legendary"] == True]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [50]:
#Pokemon leggendari di tipo 1 Grass
pokemon_df[(pokemon_df["Legendary"] == True) & (pokemon_df["Type 1"] == "Grass")]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True

In [52]:
#Pokemon di tipo 1 Ice o Fire
pokemon_df[(pokemon_df["Legendary"] == True) & ((pokemon_df["Type 1"] == "Ice") | (pokemon_df["Type 1"] == "Fire"))]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True
485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [53]:
#Settola colonna Name nell'indice
pokemon_df.set_index("Name", inplace=True)

In [54]:
#Pokémon della prima generazione con attacco > 50 e HP < 60
pokemon_df[(pokemon_df["Generation"] == 1) & (pokemon_df["Attack"] > 50) & (pokemon_df["HP"] < 60)]

,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False
Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False
Paras,Bug,Grass,285,35,70,55,45,55,25,1,False
Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
Dugtrio,Ground,NaN,405,35,80,50,50,70,120,1,False
Psyduck,Water,NaN,320,50,52,48,65,50,55,1,False
Mankey,Fighting,NaN,305,40,80,35,35,45,70,1,False
Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
Geodude,Rock,Ground,300,40,80,100,30,30,20,1,False
Graveler,Rock,Ground,390,55,95,115,45,45,35,1,False
Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
Magneton,Electric,Steel,465,50,60,95,120,70,70,1,False
Farfetch'd,Normal,Flying,352,52,65,55,58,62,60,1,False
Doduo,Normal,Flying,310,35,85,45,35,35,75,1,False
Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
Kingler,Water,NaN,475,55,130,115,50,50,75,1,False
Hitmonlee,Fighting,NaN,455,50,120,53,35,110,87,1,False
Hitmonchan,Fighting,NaN,455,50,105,79,35,110,76,1,False
Koffing,Poison,NaN,340,40,65,95,60,45,35,1,False
Seadra,Water,NaN,440,55,65,95,95,45,85,1,False
Goldeen,Water,NaN,320,45,67,60,35,50,63,1,False
Eevee,Normal,NaN,325,55,55,50,45,65,55,1,False
Kabuto,Rock,Water,355,30,80,90,55,45,55,1,False
Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False